# Generated by Django 5.1 on 2024-12-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('father', '0002_alter_element_bucket_alter_element_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
